export default {
login: "RunalBandishti",
id: 42735893,
node_id: "MDQ6VXNlcjQyNzM1ODkz",
avatar_url: "https://avatars.githubusercontent.com/u/42735893?v=4",
gravatar_id: "",
url: "https://api.github.com/users/RunalBandishti",
html_url: "https://github.com/RunalBandishti",
followers_url: "https://api.github.com/users/RunalBandishti/followers",
following_url: "https://api.github.com/users/RunalBandishti/following{/other_user}",
gists_url: "https://api.github.com/users/RunalBandishti/gists{/gist_id}",
starred_url: "https://api.github.com/users/RunalBandishti/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/RunalBandishti/subscriptions",
organizations_url: "https://api.github.com/users/RunalBandishti/orgs",
repos_url: "https://api.github.com/users/RunalBandishti/repos",
events_url: "https://api.github.com/users/RunalBandishti/events{/privacy}",
received_events_url: "https://api.github.com/users/RunalBandishti/received_events",
type: "User",
site_admin: false,
name: "Runal Bandishti",
company: null,
blog: "",
location: "Pune",
email: null,
hireable: null,
bio: "Just WokeUp & Scheduling Myself.!",
twitter_username: null,
public_repos: 14,
public_gists: 0,
followers: 1,
following: 3,
created_at: "2018-08-27T09:25:57Z",
updated_at: "2021-06-12T08:44:28Z"
};
